### ISSUE TITLE
Nothing happens when updates/inserts/removes when offline

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#18]
I use this kind of snippet and it doesn't work:

```js
export createContainer((props) => {
  const sub = subscribeCached(MeteorStore, 'example', {user: 'Mikey'});
  return {
    docs: Meteor.collection('docs').find({}),
  };
}, component)
```

**Comment by JulianKingman** [comment]
I wouldn't expect them to work, right now it's pretty much read-only. Perhaps I should throw an error if someone tries to manipulate the database?

**Comment by balibou** [comment]
mmm no need for an error I think ...
Any plan for making it work in the future ?

**Comment by JulianKingman** [comment]
The complicated part is how to know what updates to apply and which to ignore. For example, someone updates a document while offline, then later updates via the web app, then later the phone syncs. Which update(s) do you apply? How do you handle conflicts? So, maybe. I could set it up, but it would be a risky feature to use because of the potential unintended consequences.
