### ISSUE TITLE
[Realm branch] Improvements

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#23]
I checked some stuff yesterday, and here are some improvements that can considerably boost the perf (connectMeteorRedux.js):

1. line 103 - The developer should create his own schema. The package shouldn't create them automatically. (reason: better structure, and possibility to custom property of the Realm object)

2. line 152 - Prefer for loop with cached length over forEach ([jsperf](https://jsperf.com/for-vs-foreach/37))
```
length = values.length;
for (i = 0; i < length; i++) {
    sum += values[i];
}
```

3. line 182 - Don't use stringify, because this is exactly the behavior of Asynctorage we want to avoid (stringify and parsing data). Reference to the point 1. let the user create his own schema

[PS]: I know this is a lot of work to do again but I'm pretty sure it is definitely worthy for boosting perf a lot.

some sources:
- https://hellokoding.com/todo-app-with-react-native-realm/
- https://medium.com/@bosung90/tackling-react-native-storage-part-1-d27b2bfa480f#.6ws1blmqt

**Comment by JulianKingman** [comment]
If you look closer, the schema just defines collections and documents, allowing for an artitrary number of collections and an arbitrary document shape, making it more compatible with the "meteor way". I feel like defining a shema for every collection is very "stiff", especially because schema are declared differently in realm than Mongo. Maybe I'll test the stringify stuff, to see if it's really a performance bottleneck. My theory is/was that because I store each doc separately (compared to asyncstorage), keyed by id, it would perform pretty well. 

The for loop shouldn't be a problem.

**Comment by balibou** [comment]
Right ...
Mmm I don't really know then ...
I will try to make the thing working without going throught the package and compare to the code of connectMeteorRedux.js ...

**Comment by JulianKingman** [comment]
Here's a jsperf on JSON.stringify: https://jsperf.com/json-stringify-versions/3
93,759 operations per second should be fast enough :)
Also, looking at the `forEach` again, it's just looping through the collections, of which there likely won't be many, so not a lot lost there.

One thing we could try is throttling saves, so they're added in bulk on a timer, instead of on every DDP addition/update/removal (mainly the initial load is the problem, since it fires an 'added' event for every downloaded document.

On the 'restore' side, I still don't know why it's so slow. Is it actual disk write speeds, or... something else? This is the main problem.

**Comment by balibou** [comment]
Ahah yes, but there is the parsing process to take into account too :)
[WITHOUT REALM]
I've tried with 10 and 100 objects in Asyncstorage and the performances are totally different ! (stringify and parse)

[WITH REALM]
I have rendered 10 and 100 objects using same schema I used in simple schema on meteor and there are absolutely no problem ! (absolutely no use of stringify)

**Comment by JulianKingman** [comment]
Any code you can share?

**Comment by JulianKingman** [comment]
Also, I don't really notice a performance issue until over 1000 records

**Comment by balibou** [comment]
It was just shitty tests but I will do it :)

**Comment by JulianKingman** [comment]
So there's this related issue: https://github.com/realm/realm-js/issues/491
Basically, with the chrome debugger enabled, realm performs much much much slower. Testing this on the example (for which I added a setting that creates 10,000 records), performance is pretty snappy. Give it a shot and let me know how it works.
Hopefully they fix it soon, as never enabling debugger would be rather unfortunate.

**Comment by balibou** [comment]
Yes, but even if I remove chrome debugger / or run it on my iphone, it's pretty laggy ...

**Comment by JulianKingman** [comment]
How many records are you dealing with, and how big are the objects? I'm seeing next to 0 performance hit for the 10,000 moderate/large objects.

**Comment by balibou** [comment]
Sorry for the delay ...
just 100 objects, but with nested objects and arrays inside.
I will provide you an example as soon as I can

**Comment by JulianKingman** [comment]
Huh, 100 should be no problem. Is it a repo you can share? It seems like maybe something else is going on

**Comment by balibou** [comment]
Yeah but with the error "Document.fields must be of type: string" it won't actually work on my repo ...

**Comment by JulianKingman** [comment]
Give v2.0 a try. It has a different API, so be aware of that.

**Comment by balibou** [comment]
Cool ! Thanks will have a try this week end :)

**Comment by JulianKingman** [comment]
I'm going to close this. Although realm is somewhat attractive b/c of improved performance, I think v2 improves it enough that this is no longer necessary; it's also unclear just how much we can improve performance just by using realm, I think the bottleneck may be elsewhere. Plus, doing away with an extra `react-native link` means this can be used in expo.
